markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 技术宅
host: http://elliclee.github.com
desc: Coding the future

custom:
    category:
        writing: 文字记录
        tech: 技术记录
        sharing: 技术分享
    categories:
      - name:  writing
        title: 文字记录

      - name:  tech
        title: 技术记录

      - name:  sharing
        title: 技术分享

meta:   
    author:
        name: ellic
        email: ellic@outlook.com
        disqus: ellicgithub              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: elliclee                 # GitHub账号
        gravatar: bbbda49f651462395d661226f2ea1354  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
